Algoritmo "semnome"


Var

//declarar variáveis
nome, sexo: caracter
idade: inteiro
salario: real
casado: logico


Inicio

//atribuir algum valor às variáveis
nome := "Alfredo Jozefo"
sexo := "M"
idade := 3589
salario := 10000
casado := Falso


//printar
escreval("Só printando valor das variáveis")
escreval("--------------------------------")
escreval("Nome = ",nome)
escreval("Sexo = ",sexo)
escreval("Salário = R$ ",salario:4:2)
escreval("Casado [VERDADEIRO/FALSO] = ",casado)



Fimalgoritmo