Algoritmo "CombinacoesNemN"

//ESSE PROGRAMA SERVE PARA FAZER COMBINAÇÕES COM 2 LAÇOS PARAS DE 4 EM 4
//PARA AUMENTAR O NÚMERO DE POSSIBILIDADES DE COMBINAR É SÓ AUMENTAR NOS
//LAÇOS PARA

Var

//variáveis globais
l, c: inteiro

Inicio

//laço para fazer combinações de 2 laços de 4 em 4
Para l de 1 ate 4 Faca
     Para c de 1 ate 4 Faca
          Escreva(l,c)
          Escreval()
     FimPara
     Escreval()
FimPara


Fimalgoritmo