Algoritmo "semnome"


Var

//declarar variáveis
num1, num2: real

Inicio


//ler numeros
escreva("Digite um número: ")
leia(num1)
escreval()
escreva("Digite o outro número: ")
leia(num2)


//printar resultado de operações aritméticas básicas
escreval()
escreval(num1," + ",num2," = ",num1+num2)
escreval(num1," - ",num2," = ",num1-num2)
escreval(num1," * ",num2," = ",num1*num2)
escreval(num1," / ",num2," = ",num1/num2)



Fimalgoritmo